Adam review component
UhOhDonovan/soundtrackd-frontend pull request #2
Opened 2024-11-29 02:12 UTC by adam-burton-stl

Create a component to display reviews and add it to the album page.
Reviews do not yet dynamically grab review data, but can display it when given it.
API endpoint to grab the data needs to be created still.
Minor tweaks to the album page component as well.

2024-11-29 19:31 UTC, UhOhDonovan requested changes
I don't want template features pulled into main quite yet. Go ahead and integrate the review component with the backend before you request another review

2024-12-03 03:14 UTC, UhOhDonovan commented on src/components/Album.vue
> +      if (result != ""){
Use of wrong operator, use "!==" so that it doesn't evaluate to true in falsey types.

2024-12-03 03:15 UTC, UhOhDonovan commented on src/components/Review.vue
> +  id: Number,
Are these data types part of vue? What are they for?

2024-12-03 03:22 UTC, adam-burton-stl commented on src/components/Review.vue
> +  id: Number,
They were for typescript so it wouldn't freak out about accessing object properties that could possibly not exist. The album one is a subset of the properties in the JSON object received from Spotify. Should be removed probably, but I have a habit of commenting out instead of deleting.

2024-12-03 07:05 UTC, adam-burton-stl commented
Oops I made all of these changes to a different branch that is ahead of this one, I will pull request that branch instead.

2024-12-03 07:19 UTC, merged